### ISSUE TITLE
Contact Line - Don't have a GitHub link

### ISSUE THREAD

**Issue by alfavita21** [cystema/PlushCV#1]
Hello, thank you for this really good looking template.

I'm trying to build a CV however my candidate does not have a GitHub link to add to \contactline. 

When I try to remove the part of the string where the GitHub link sits, the whole line is removed.

How can I keep the rest of the links but not include the GitHub one?

Thanks again,
alfavita21

**Comment by lomky** [comment]
The way this template is formatted you must edit both the tex and cls file if you remove or reorder the contact line.

For anything you remove from here
https://github.com/sansquoi/PlushCV/blob/c7a9a3f3c0439ea2c6a1567877cc4f2995959a28/PlushCV.tex#L48

You must edit the class to change the array size, correct the array placement, and remove the unneeded line.

https://github.com/sansquoi/PlushCV/blob/c7a9a3f3c0439ea2c6a1567877cc4f2995959a28/PlushCV.cls#L214-L221

So to remove the GitHub you would do:

```latex
 \namesection{Firstname}{Lastname}{Full Stack Software Engineer}{\contactline{\href{https://www.home.me}{homepage.com}}{\href{https://www.linkedin.com/}{li-username}}{\href{mailto:first.last@mail.com}{first.last@email.com}}{\href{tel:+1999999999}{9999999999}}} 
```
and

```latex
\newcommand{\contactline}[4]{\begingroup 
 \setbox0=\hbox{ 
 \includegraphics[scale=0.23,trim={1.4cm 1.25cm -0.4cm 0cm}]{icons/main/home.png}{#1}\hspace{0.3cm} 
 \includegraphics[scale=0.23,trim={0cm 1.25cm -0.4cm 0cm}]{icons/main/linkedin.png}{#2}\hspace{0.3cm} 
 \includegraphics[scale=0.23,trim={0cm 1.25cm -0.4cm 0cm}]{icons/main/mail.png}{#3}\hspace{0.3cm} 
 \includegraphics[scale=0.23,trim={0cm 1.25cm -0.4cm 0cm}]{icons/main/phone.png}{#4} 
 }\parbox{\wd0}{\box0}\endgroup} 
```

**Comment by cystema** [comment]
@lomky thanks!
