### ISSUE TITLE
[Request]: To add support for multi page

### ISSUE THREAD

**Issue by theetherGit** [cystema/PlushCV#5]
I know you already have this in mind but i really need it. I have been using this template for long time and now i'm need of second page content. So, please i really need it.
Thank You

**Comment by cystema** [comment]
Hi! This resume is not optimal for ATSs so I would probably not be working on it further. However, I am working on a new single-column template that is better optimized for ATS (and also does not have multi-page issues). You could use that if you like.

**Comment by theetherGit** [comment]
Thank you so much. Can you please share new template link?

**Comment by cystema** [comment]
Sure, I'll try to upload it by today.

**Comment by theetherGit** [comment]
Ok.

**Comment by cystema** [comment]
@theetherGit Sorry for the wait, but here's the new template: https://github.com/sansquoi/AustereCV.
